### ISSUE TITLE
Add sphinx for documentation

### ISSUE THREAD

**Issue by tkilias** [exasol/bucketfs-utils-python#29]
## Background

- Sphinx is a standard documentation system for python https://www.sphinx-doc.org/en/master/
- It provides documentation generation from reStructuredText or markdown
- It can generate menus
- It can generate api documentation from python docstrings
- It can generate documentation for Readthedocs https://readthedocs.org/

## Acceptance Criteria

- [x] - Have a working setup for sphinx with api documentation generation
- [x] - Additional contents:
- [x]   - Installation, Usage, Developer Guide 
- [x] - CI tasks which generates the documentation 
- [x] - Optional: get it published on github pages

**Comment by redcatbear** [comment]
@tkilias, please provide description.
