### ISSUE TITLE
Correct mock bucketfs upload method

### ISSUE THREAD

**Issue by umitbuyuksahin** [exasol/bucketfs-utils-python#63]
# Background

- An infinite loop occurs, while reading a file object chunk by chunk in the line shown below.
- The reason of the infinite loop is that the senitel character of the iter method is not correct. It should be `b''`, instead of ' '.

https://github.com/exasol/bucketfs-utils-python/blob/7ac95f606d3082e5fa1b4136be748732e20de713/exasol_bucketfs_utils_python/localfs_mock_bucketfs_location.py#L57

# Acceptance Criteria

- Fixed the error
- Add unit tests regarding this method

**Comment by tkilias** [comment]
Do you mean `b''` or `b' '`?

**Comment by umitbuyuksahin** [comment]
it is a typo, it must be `b' '`
